### PR TITLE
Upgrade MEJS to 4.2.5

### PR DESCRIPTION
**Pull request by rafa8626**
https://core.trac.wordpress.org/ticket/39686

### CODE REVIEW

**Comment by rafa8626** [comment]
This PR solved some issues found in MediaElement by the users, including:
- Set current time properly for YouTube live streams
- Fixed issue related to iframe renderers not resizing properly after using fullscreen
- Removed unnecessary event un-bindings that caused errors on MS Edge

**Comment by westonruter** [comment]
@rafa8626 are more releases expected in the next weeks?

**Comment by rafa8626** [comment]
No this is the last one I will do

**Comment by westonruter** [comment]
Note there was one other change needed:

```diff
diff --git src/wp-includes/script-loader.php src/wp-includes/script-loader.php
index a080c53d71..c3d05ae264 100644
--- src/wp-includes/script-loader.php
+++ src/wp-includes/script-loader.php
@@ -949,7 +949,7 @@ function wp_default_styles( &$styles ) {
 	// External libraries and friends
 	$styles->add( 'imgareaselect',       '/wp-includes/js/imgareaselect/imgareaselect.css', array(), '0.9.8' );
 	$styles->add( 'wp-jquery-ui-dialog', "/wp-includes/css/jquery-ui-dialog$suffix.css", array( 'dashicons' ) );
-	$styles->add( 'mediaelement',        "/wp-includes/js/mediaelement/mediaelementplayer-legacy.min.css", array(), '4.2.3' );
+	$styles->add( 'mediaelement',        "/wp-includes/js/mediaelement/mediaelementplayer-legacy.min.css", array(), '4.2.5' );
 	$styles->add( 'wp-mediaelement',     "/wp-includes/js/mediaelement/wp-mediaelement$suffix.css", array( 'mediaelement' ) );
 	$styles->add( 'thickbox',            '/wp-includes/js/thickbox/thickbox.css', array( 'dashicons' ) );
```

**Comment by westonruter** [comment]
Committed to `trunk` in r41240.

**Comment by rafa8626** [comment]
Thanks for bringing this up. I may have another branch coming with one or 2 more fixes but I'm still testing. That might be the last branch I'll submit given the tests I've done

**Comment by westonruter** [comment]
> No this is the last one I will do

You lied to me 😄

**Comment by gordielachance** [comment]
Is there a patch file I could run to test this ?

**Comment by rafa8626** [comment]
I assume that since it has been merged to the trunk you can test the 4.9 version using a Vagrant instance via https://github.com/Varying-Vagrant-Vagrants/VVV @westonruter any other advise?

**Comment by westonruter** [comment]
Yes. You can try `trunk` on `wordpress-develop`, but it is probably easier to try a nightly build: https://make.wordpress.org/core/handbook/testing/beta/

**Comment by gordielachance** [comment]
Hi Weston, thanks.
I did try to upgrade with the Beta tester plugin and it installed the '4.8.2-alpha-41212'.  I guess this is not the version I should have installed ?

**Comment by westonruter** [comment]
@gordielachance no, that's not right. Point number 5 note it says:

> Select the  “Bleeding edge nightlies” option to follow development for the next major release of WordPress, or “Point release nightlies” to follow development of the next point release.

It seems you have selected “Point release nightlies” when you should instead select “Bleeding edge nightlies”. Once you've done so, you should see '4.9-alpha...' as the version.

**Comment by gordielachance** [comment]
@westonruter Ok I got it, thanks !
From what I see, everything works fine with medialelementjs.  I'll let you know today or tomorrow if I find something weird.

**Pull request closed without merging**
