### PR TITLE
Trac 39686: Upgrade MediaElement to 4.X

### PR DESCRIPTION
**Pull request by westonruter**
https://core.trac.wordpress.org/ticket/39686

### CODE REVIEW

**Comment by westonruter** [comment]
YouTube video fails to render in post content (`[video src="http://youtube.com/watch?v=i_cVJgIz_Cs"]`):

image

YouTube video in widget is overflowing:

image

Vimeo in post content and video alike fails to render entirely (`[video src="http://www.vimeo.com/108650530"]`):

image

**Comment by rafa8626** [comment]
@westonruter I tested YouTube on the Admin area and it looks good. However, Vimeo renders in the Admin area but it's not using MEJS. If I go to the Preview, I see it's using it but it's using an old version under the 20/17 theme. How can I check this under the new files?

**Comment by rafa8626** [comment]
Disregard my last comment I was using local URL instead of src URL

**Comment by rafa8626** [comment]
@westonruter FYI I had fixed the Vimeo issue, so it should be fine; only thing I noticed is that the `iframe` gets cut on the Admin area a little but I don't where to check this and attempt to fix it. Can you assist on this, please?
screen shot 2017-05-27 at 12 16 00 pm
screen shot 2017-05-27 at 12 16 07 pm

**Comment by rafa8626** [comment]
I got it fixed with the last commit. I have tested some other videos, and seems to be working. Let me  know if you need anything else from me

**Comment by westonruter** [comment]
@rafa8626 thanks. It seems to be fixed in the post editor, but the YouTube and Vimeo videos are still not showing properly on the frontend.

Given `[video src="http://youtube.com/watch?v=i_cVJgIz_Cs"]` or `[video src="http://www.vimeo.com/108650530"]`, I can get the audio to play only. The video is blank:

image
 
But when appearing in the Video widget, the YouTube video seems to play now but the Vimeo doesn't (widget with Vimeo shown before widget with YouTube):

image

**Comment by westonruter** [comment]
Also there is a unit test that is failing now: https://travis-ci.org/xwp/wordpress-develop/jobs/236705873#L714

**Comment by rafa8626** [comment]
I'll test this and fix it. Which browser you are using? Because I tried Chrome, FF and Safari on Mac OSX and it went well

**Comment by westonruter** [comment]
Chrome on OSX, with the Twenty Sixteen theme active.

**Comment by rafa8626** [comment]
Weird. I see everything working fine using Chrome and the same theme. Attaching screenshots. The test should be fixed now. If there are any steps I may be missing please let me know.
screen shot 2017-05-28 at 12 44 51 pm
screen shot 2017-05-28 at 12 45 17 pm

**Comment by rafa8626** [comment]
I have tested all the themes and all are working for me. Is there anything else I can help you with?

**Comment by rafa8626** [comment]
@westonruter I found out 2 more places where Froogaloop is being referenced; one of them was fixed in my last commit, but I don't know abut the other one(which is on `wp-includes/js/media/views/media-details.js`). Should this one be updated as well? I have tried to output something to see if it's needed but I haven't had any luck. And I've been only interacting with the Edit Post area. Let me know if you have any hints about this. Thanks

**Comment by westonruter** [comment]
@rafa8626 yes, that reference in `media-details.js` should also be updated.

I'm still having the issue with the YouTube and Vimeo players not being shown. Here is what I see:

image

Notice the `iframe` is getting `0` for its `width` and `height`. If I manually change them then I can see the player.

**Comment by rafa8626** [comment]
Ok I'll update that. As for the issue I'd like you to list all the steps you are taking to attempt to reproduce this, and also the theme you are using please. It's odd that I'm not having this issue and you are

**Comment by rafa8626** [comment]
Also if I change the reference of Froogaloop, where can I test the end result? I haven't been able to print a debugging line I set up for testing purposes

**Comment by rafa8626** [comment]
I mean which section on Wordpress could reflect this, and how if I have to do more than copy/paste something?

**Comment by westonruter** [comment]
> Also if I change the reference of Froogaloop, where can I test the end result? I haven't been able to print a debugging line I set up for testing purposes

I can't seem to find where `MediaDetails#setPlayer` method gets called.

**Comment by westonruter** [comment]
> Ok I'll update that. As for the issue I'd like you to list all the steps you are taking to attempt to reproduce this, and also the theme you are using please. It's odd that I'm not having this issue and you are

Activate Twenty Sixteen and then publish a post that contains the following shortcodes:

```
[video src="http://youtube.com/watch?v=i_cVJgIz_Cs"]
[video src="http://www.vimeo.com/108650530"]
```

**Comment by rafa8626** [comment]
OK since I don't know if the Froogaloop piece I mentioned is being used, I won't touch it. I tried to reproduce the issue you are having but I can't. Here's my result. I tried adding 50 videos and all of them worked.
screen shot 2017-06-04 at 12 03 06 am

**Comment by rafa8626** [comment]
@westonruter I don't know what to say since I haven't been able to reproduce this. As a side note, the new version is coming soon and that fixed an issue with YouTube URLs, so I'll update this PR soon. Let me know if there's anything else I can do

**Comment by rafa8626** [comment]
@gordielachance Can you assist me on testing this PR according to https://core.trac.wordpress.org/ticket/39686#trac-change-78-1496247971413326 , please? I can't reproduce the issue Weston is describing and I have followed his instructions. If you can reproduce it, let me know. Try adding even 50 videos on the same post using Theme 20/16 and using the shortags
```
[video src="http://youtube.com/watch?v=i_cVJgIz_Cs"]
[video src="http://www.vimeo.com/108650530"]
```
Please keep me posted

**Comment by gordielachance** [comment]
Yes, i'll have a look this evening or tomorrow morning.

**Comment by rafa8626** [comment]
Thanks

**Comment by gordielachance** [comment]
Hi guys, I had a look on this.
Added videos using the visual editor backend, with those URLs:

[video src="https://www.youtube.com/watch?v=tDjM-3a9Jw8"]
[video src="https://vimeo.com/218597363"]

I can play the videos in the editor and I hear the sound.
Frontend, it worked with a custom theme, with Twenty Seventeen, Twenty Sixteen and Twenty Fifteen.

I noticed a small bug though : on Twenty Seventeen and Sixteen (not Fifteen), the hover status of the player icons has a bug : it display a kind of square (grey on Seventeen, blue on Sixteen) where the icon is no more visible.  It remains that way until you click somewhere on the page :
capture d ecran 2017-06-05 a 10 13 17

**Comment by rafa8626** [comment]
Ok I can take a look at that but you were able to see videos properly (with the exception of that small bug) correct?

**Comment by gordielachance** [comment]
Yes yes,I did.

**Comment by rafa8626** [comment]
@gordielachance Thanks for testing this. I'll check that small issue today, can you put a comment on WP ticket about your testing, please? Just to keep record of it

**Comment by rafa8626** [comment]
@gordielachance I tried to hover the icons but I haven't seen the grey/blue issue; do I have to do something specifically?

**Comment by rafa8626** [comment]
I haven't seen any issues so far; Weston are we good on this?

**Comment by rafa8626** [comment]
@westonruter I tried something else that I didn't before: Video Widget. It will work without issues but there's a line that is not catching the right mime type (https://github.com/xwp/wordpress-develop/blob/master/src/wp-includes/functions.php#L2229). I don't wanna touch that since I don't know what are the implications of modifying it. This regex breaks the Widget because when using the widget is appending the `loop` argument by default and that doesn't match the regex. What can we do?

**Comment by westonruter** [comment]
@rafa8626 what is the input you provided for the video widget? Are you providing an external URL to a video file?

The `loop` arg was being added to fix an issue with Vimeo not honoring the loop setting. You can see it was introduced here: https://github.com/xwp/wp-core-media-widgets/commit/dddaa8868e4f7d20e17fab7a1e14109ff11d42c4

See pull request https://github.com/xwp/wp-core-media-widgets/pull/136

If the Vimeo looping issue has been fixed in ME.js which apparently it has in https://github.com/instructure/mediaelement/pull/17 then that whole patch can just be reverted.

**Comment by rafa8626** [comment]
@westonruter I sued an external URL for an MP4 video (https://media.w3.org/2010/05/sintel/trailer.mp4) I'll check that PR and revert locally; if I see that the `loop` issue has been fixed, I'll push the reverted code on this branch. Is that OK?

**Comment by westonruter** [comment]
@rafa8626 yes, it makes sense to remove that `loop` workaround in the same patch that also updates ME.js which eliminated the need for the `loop` workaround in the first place.

**Comment by rafa8626** [comment]
OK I'm on that right now; and I'm also removing the Froogaloop reference. I 'll submit this in a minute

**Comment by westonruter** [comment]
@rafa8626 removing the Froogaloop reference or _updating_ the reference? There is a new JS file that is needed or Vimeo that replaces Froogaloop, no?

**Comment by rafa8626** [comment]
Sorry I meant replacing it

**Comment by rafa8626** [comment]
In the end, having the vimeo.min.js solves the need for Froogaloop, since that's deprecated. I'll test without that line at all

**Comment by rafa8626** [comment]
@westonruter Hmmmm I don't know if it makes sense to keep the conditional at all. The libraries we are using (including `renderers/vimeo.js` that is already being loaded) already solve this, so I'm not sure. Thoughts?

**Comment by rafa8626** [comment]
And I haven't found yet the place where this is being executed, have you?

**Comment by rafa8626** [comment]
Well I have replaced the instances at this point with the new approach. It should be fine

**Comment by rafa8626** [comment]
@westonruter I did a little clean up and fixed the conflicts on the branch; let me know if you need anything else, please

**Comment by westonruter** [comment]
Main thing is it needs wider testing and review by core contributors, in particular those in the `#core-media` Slack channel and Media component maintainers.

**Comment by rafa8626** [comment]
Gotcha. Well I have asked who needs to review this so let me know if there's anything else I can do

**Comment by westonruter** [comment]
Committed to trunk in r41198.

**Comment by gordielachance** [comment]
...which means it is finally merged ???
If yes, thanks !!!

**Comment by westonruter** [comment]
@gordielachance yes, it has been merged. It will be part of WordPress 4.9. It will now get testing in 4.9-alpha and the subsequent beta releases.

**Pull request closed without merging**
