### PR TITLE
#36944: Display server-sent Customizer setting validation errors before save is attempted

### PR DESCRIPTION
**Pull request by westonruter**
https://core.trac.wordpress.org/ticket/36944

### CODE REVIEW

**Comment by westonruter** [comment]
Committed to core in r37700.

**Comment by ahmadawais** [comment]
@westonruter OFF TOPIC: How do you notify people involved in the ticket on GitHub Pull requests like this one?

**Comment by westonruter** [comment]
@ahmadawais I usually link to the PR when I'm uploading the patch to a ticket:

_36944__display_server-sent_customizer_setting_validation_errors_before_save_is_attempted__ _wordpress_trac

Recently GitHub started including the URL to the PR as the base URL before the commit itself. Previously I would like to both the PR and the commit. But now I can just link to the commit in the context of the PR.

**Comment by ahmadawais** [comment]
Great. And that sends a notification to people on GitHub as well?

**Comment by westonruter** [comment]
@ahmadawais Not sure I understand. If people are watching the GitHub repo, the XWP clone of the WordPress Git repo, then yes they would get notified when a PR is opened. But watchers on GitHub would not be notified when a patch from a GitHub PR is uploaded and linked to from a Trac ticket.

**Comment by ahmadawais** [comment]
Got it. I forgot I was watching this repo and thought you might be notifying us all in some way that connects Trac watchers with GitHub. Got it.

**Pull request closed without merging**
